### ISSUE TITLE
tldoc can't parse valid schema

### ISSUE THREAD

**Issue by joeberetta** [Bannerets/ti-el#1]
First of all, thank you for this project.

I'm getting this error for schema downloaded from Telegram's documentation. By the way, tl-parser and tl-transform packages are ok for this part.

```js
Error: No arg.id
    at normalizeArgument (/Users/joeberetta/work/tl-docs/node_modules/tldoc/dist/index.js:108:37)
    at Array.map (<anonymous>)
    at normalizeCombinator (/Users/joeberetta/work/tl-docs/node_modules/tldoc/dist/index.js:128:26)
    at /Users/joeberetta/work/tl-docs/node_modules/tldoc/dist/index.js:83:43
    at Array.map (<anonymous>)
    at combinatorsFromAST (/Users/joeberetta/work/tl-docs/node_modules/tldoc/dist/index.js:83:34)
    at exports.tldoc (/Users/joeberetta/work/tl-docs/node_modules/tldoc/dist/index.js:153:23)
    at Object.<anonymous> (/Users/joeberetta/work/tl-docs/index.js:10:13)1```
```

For debugging added console log of argument and got, that it throws on parsing Vector type: declaration which has no id (it's null) 
```tl
vector#1cb5c415 {t:Type} # [ t ] = Vector t;
```

```js
{
  type: 'Argument',
  start: { offset: 1243, line: 36, column: 26 },
  end: { offset: 1244, line: 36, column: 27 },
  id: null,
  conditionalDef: null,
  term: {
    type: 'TypeTerm',
    start: { offset: 1243, line: 36, column: 26 },
    end: { offset: 1244, line: 36, column: 27 },
    term: {
      type: 'TypeIdentifier',
      start: [Object],
      end: [Object],
      name: '#'
    }
  },
  multiplicity: null,
  subargs: null,
  ids: null
}
```

Hope the project is not abandoned, many thanx

**Comment by Bannerets** [comment]
Hi! If I recall correctly, tldoc doesn't support `vector` types, since it's not possible to document the arguments if they are unnamed (the arguments `#` and `[ t ]` are unnamed). The workaround is to remove the definition of `vector` from the scheme manually. For example, [this thing](https://github.com/Bannerets/tdl/blob/5c5063d0fb6856be4d42afc63ae60295275f6137/packages/tdlib-types/src/lib.js) uses tldoc to generate TS types with documentation comments from a [TDLib scheme](https://github.com/tdlib/td/blob/fce20df018a8ec23e440637e3557694ab36b44f4/td/generate/scheme/td_api.tl).

I'm sorry that's a bit inflexible. This project is pretty much abandoned and was meant to be replaced by [this parser](https://github.com/Bannerets/camlproto/tree/54d46860ff3e2ca1b7936764fa97b205e11ddb61/src/tl/lib) written in OCaml (it can also replace `tdl/packages/tdlib-types`), but I haven't had the time to implement the parsing of the documentation comments there.

**Comment by joeberetta** [comment]
Hi @Bannerets and thanks for quick reply.
It's sad to hear that project is abandoned, cuz I found it and it's almost perfect solution for my cases:
* Generating documentation from tl schema
* Generating TS typings and functions for using them

Is it ok, if I fork it and rewrite using TS?

**Comment by Bannerets** [comment]
> Is it ok, if I fork it and rewrite using TS?

Yeah, sure!
